"""Ajout date_fin_consultation à la table consultation

Revision ID: f3dd99779e0b
Revises: 
Create Date: 2025-07-08 03:47:34.160940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3dd99779e0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ambulancier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email_ambulancier'))

    op.drop_table('ambulancier')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email_admin'))

    op.drop_table('admin')
    with op.batch_alter_table('interne_medecine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email_interne'))

    op.drop_table('interne_medecine')
    with op.batch_alter_table('gestionnaire_logistique', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email_logistique'))

    op.drop_table('gestionnaire_logistique')
    with op.batch_alter_table('infirmier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email_infirmier'))

    op.drop_table('infirmier')
    with op.batch_alter_table('gestionnaire_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email_stock'))

    op.drop_table('gestionnaire_stock')
    with op.batch_alter_table('caissier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email_caissier'))

    op.drop_table('caissier')
    with op.batch_alter_table('secretaire_medicale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email_secretaire'))

    op.drop_table('secretaire_medicale')
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_fin_consultation', sa.Date(), nullable=True))

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.alter_column('date_inscription',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('date_inscription',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('date_inscription',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.alter_column('date_inscription',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.drop_column('date_fin_consultation')

    op.create_table('secretaire_medicale',
    sa.Column('ident', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom_utilisateur', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('email_secretaire', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('date_inscription', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom_complet', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=225), nullable=True),
    sa.Column('date_naissance', sa.DATE(), nullable=True),
    sa.Column('sexe', mysql.ENUM('Homme', 'Femme'), nullable=True),
    sa.Column('situation_matrimoniale', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('photo', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('description', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('adresse', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('pays', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('ville', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('code_postal', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('numero_telephone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('heure_debut_dimanche', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_dimanche', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_lundi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_lundi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_mardi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_mardi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_mercredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_mercredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_jeudi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_jeudi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_vendredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_vendredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_samedi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_samedi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.PrimaryKeyConstraint('ident'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('secretaire_medicale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email_secretaire'), ['email_secretaire'], unique=True)

    op.create_table('caissier',
    sa.Column('ident', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom_utilisateur', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('email_caissier', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('date_inscription', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom_complet', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=225), nullable=True),
    sa.Column('date_naissance', sa.DATE(), nullable=True),
    sa.Column('sexe', mysql.ENUM('Homme', 'Femme'), nullable=True),
    sa.Column('situation_matrimoniale', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('photo', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('description', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('adresse', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('pays', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('ville', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('code_postal', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('numero_telephone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('heure_debut_dimanche', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_dimanche', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_lundi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_lundi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_mardi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_mardi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_mercredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_mercredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_jeudi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_jeudi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_vendredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_vendredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_samedi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_samedi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.PrimaryKeyConstraint('ident'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('caissier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email_caissier'), ['email_caissier'], unique=True)

    op.create_table('gestionnaire_stock',
    sa.Column('ident', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom_utilisateur', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('email_stock', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('date_inscription', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom_complet', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=225), nullable=True),
    sa.Column('date_naissance', sa.DATE(), nullable=True),
    sa.Column('sexe', mysql.ENUM('Homme', 'Femme'), nullable=True),
    sa.Column('situation_matrimoniale', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('photo', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('description', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('adresse', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('pays', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('ville', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('code_postal', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('numero_telephone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('heure_debut_dimanche', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_dimanche', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_lundi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_lundi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_mardi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_mardi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_mercredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_mercredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_jeudi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_jeudi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_vendredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_vendredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_samedi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_samedi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.PrimaryKeyConstraint('ident'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('gestionnaire_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email_stock'), ['email_stock'], unique=True)

    op.create_table('infirmier',
    sa.Column('ident', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom_utilisateur', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('email_infirmier', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('date_inscription', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom_complet', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=225), nullable=True),
    sa.Column('date_naissance', sa.DATE(), nullable=True),
    sa.Column('sexe', mysql.ENUM('Homme', 'Femme'), nullable=True),
    sa.Column('situation_matrimoniale', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('photo', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('description', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('adresse', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('pays', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('ville', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('code_postal', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('numero_telephone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('heure_debut_dimanche', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_dimanche', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_lundi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_lundi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_mardi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_mardi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_mercredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_mercredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_jeudi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_jeudi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_vendredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_vendredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_samedi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_samedi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.PrimaryKeyConstraint('ident'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('infirmier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email_infirmier'), ['email_infirmier'], unique=True)

    op.create_table('gestionnaire_logistique',
    sa.Column('ident', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom_utilisateur', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('email_logistique', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('date_inscription', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom_complet', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=225), nullable=True),
    sa.Column('date_naissance', sa.DATE(), nullable=True),
    sa.Column('sexe', mysql.ENUM('Homme', 'Femme'), nullable=True),
    sa.Column('situation_matrimoniale', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('photo', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('description', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('adresse', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('pays', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('ville', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('code_postal', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('numero_telephone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('heure_debut_dimanche', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_dimanche', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_lundi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_lundi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_mardi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_mardi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_mercredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_mercredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_jeudi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_jeudi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_vendredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_vendredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_samedi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_samedi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.PrimaryKeyConstraint('ident'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('gestionnaire_logistique', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email_logistique'), ['email_logistique'], unique=True)

    op.create_table('interne_medecine',
    sa.Column('ident', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom_utilisateur', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('email_interne', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('date_inscription', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom_complet', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=225), nullable=True),
    sa.Column('date_naissance', sa.DATE(), nullable=True),
    sa.Column('sexe', mysql.ENUM('Homme', 'Femme'), nullable=True),
    sa.Column('situation_matrimoniale', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('photo', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('description', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('adresse', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('pays', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('ville', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('code_postal', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('numero_telephone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('heure_debut_dimanche', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_dimanche', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_lundi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_lundi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_mardi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_mardi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_mercredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_mercredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_jeudi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_jeudi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_vendredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_vendredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_samedi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_samedi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.PrimaryKeyConstraint('ident'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('interne_medecine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email_interne'), ['email_interne'], unique=True)

    op.create_table('admin',
    sa.Column('ident', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom_complet', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=225), nullable=True),
    sa.Column('email_admin', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('numero_telephone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('date_inscription', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('ident'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email_admin'), ['email_admin'], unique=True)

    op.create_table('ambulancier',
    sa.Column('ident', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom_utilisateur', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('email_ambulancier', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('date_inscription', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom_complet', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=225), nullable=True),
    sa.Column('date_naissance', sa.DATE(), nullable=True),
    sa.Column('sexe', mysql.ENUM('Homme', 'Femme'), nullable=True),
    sa.Column('situation_matrimoniale', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('photo', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('description', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('adresse', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('pays', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('ville', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('code_postal', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('numero_telephone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('heure_debut_dimanche', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_dimanche', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_lundi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_lundi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_mardi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_mardi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_mercredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_mercredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_jeudi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_jeudi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_vendredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_vendredi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_debut_samedi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('heure_fin_samedi', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.PrimaryKeyConstraint('ident'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ambulancier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email_ambulancier'), ['email_ambulancier'], unique=True)

    # ### end Alembic commands ###
